version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/app"
    schedule:
      interval: "weekly"
    versioning-strategy: increase

  - package-ecosystem: "npm"
    directory: "/agent"
    schedule:
      interval: "weekly"
    versioning-strategy: increase

  - package-ecosystem: "gomod"
    directory: "/agent-go"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
